ERR_002 | freestyleProject.cy.js | TC-001-1|Delete a project
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #105
Opened 2024-11-18 21:19 UTC by katy1313

https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/86
https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/94

2024-11-18 22:36 UTC, Negrescu29 commented on cypress/e2e/deleteFreestyleProject.cy.js
>          cy.wait(500);
@katy1313 does this `cy.wait(500)`  aka 0.5 seconds have any sense here?

2024-11-18 22:51 UTC, Negrescu29 requested changes
left comments

2024-11-18 22:51 UTC, Negrescu29 commented on cypress/e2e/deleteFreestyleProject.cy.js
>          cy.get('span').contains('New Freestyle project').should('not.exist');
@katy1313 I run this in cypress and for the assertion you have on line 17, cypress says the `span` is undefined.

<img width="409" alt="Screenshot 2024-11-18 at 23 41 42" src="https://github.com/user-attachments/assets/ef5a52ba-c4b8-4bba-89a6-89bb7d0f8750">

If I understand the logic here you want to check if the item is not shown anymore in the list after you delete it? we had a similar case in our group - you're looking at a span which in this case is the list but after you delete the item there is no list shown, just the **welcome to Jenkins** screen 




<img width="324" alt="Screenshot 2024-11-18 at 23 48 04" src="https://github.com/user-attachments/assets/839f3c8a-ca6c-4955-8d26-8d12ad2f1a2f">

I believe you can check against the welcome screen that the list is not show that means the item was deleted

2024-11-19 01:40 UTC, Negrescu29 requested changes
@katy1313 sorry just saw your spec file name, it should be the same name as the user story name. here is an example https://redroverschool.slack.com/archives/C049HHDG0KF/p1731979320828209?thread_ts=1731956893.790899&cid=C049HHDG0KF

2024-11-19 02:06 UTC, Negrescu29 approved these changes
👍🏼

2024-11-19 02:54 UTC, Rom-T approved these changes

2024-11-19 03:34 UTC, merged