TC_14.002.11-A | Header > Search Box | Verify that Dashboard page has…
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #221
Opened 2024-11-20 18:00 UTC by ElenaKhait

[… a Search box on its top right](https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/219)

2024-11-20 18:09 UTC, adiuzhikov requested changes

2024-11-20 18:09 UTC, adiuzhikov commented on cypress/e2e/headerSearchBox.cy.js
> +        cy.get('#search-box').click();
Please, add an assertion for your test from expected result: the Dashboard page has a search box on its top right.

2024-11-20 19:08 UTC, Stavolg commented on cypress/e2e/headerSearchBox.cy.js
> +      it('TC_14.002.11 | Verify that Dashboard page has a Search box on its top right', () => {
Lines 97-102 are over-indented. Align them with the rest of the test cases for consistency.

2024-11-20 19:09 UTC, Stavolg approved these changes
Сheck the indentation

2024-11-20 19:34 UTC, ElenaKhait commented on cypress/e2e/headerSearchBox.cy.js
> +      it('TC_14.002.11 | Verify that Dashboard page has a Search box on its top right', () => {
My test is on lines 97-102

2024-11-20 19:53 UTC, OlgaTsoy commented on cypress/e2e/headerSearchBox.cy.js
> +const Dashboard = '#breadcrumbBar .model-link'
I guess usually locator variables name starts from lowercase letter

2024-11-20 19:53 UTC, OlgaTsoy commented on cypress/e2e/headerSearchBox.cy.js
> +      it('TC_14.002.11 | Verify that Dashboard page has a Search box on its top right', () => {
I guess, Olga saying that you need to shift your test a little bit to the left, so it can align with all its above

2024-11-20 19:55 UTC, ElenaKhait commented on cypress/e2e/headerSearchBox.cy.js
> +      it('TC_14.002.11 | Verify that Dashboard page has a Search box on its top right', () => {
Thank you

2024-11-20 19:59 UTC, ElenaKhait commented on cypress/e2e/headerSearchBox.cy.js
> +const Dashboard = '#breadcrumbBar .model-link'
You are right)

2024-11-20 22:55 UTC, antonbloha approved these changes

2024-11-21 18:15 UTC, ElenaKhait commented on cypress/e2e/headerSearchBox.cy.js
> +        cy.get('#search-box').click();
Could you check please. Thank you

2024-11-21 20:16 UTC, ElenaKhait commented on cypress/e2e/headerSearchBox.cy.js
> +        cy.get('#search-box').click();
Artem, thank you for checking the code so carefully, can you please take a look, since all this is new, that's why there are so many shortcomings

2024-11-21 20:36 UTC, adiuzhikov approved these changes
Yes, great job!

2024-11-21 20:44 UTC, merged