TC_14.002.15_A| Header > Search Box | Verify a User can select a suggestion to auto-fill the search box and complete the search
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #301
Opened 2024-11-22 19:43 UTC by LanaUno

[TC_14.002.15](https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/293)

2024-11-22 20:17 UTC, adiuzhikov requested changes

2024-11-22 20:17 UTC, adiuzhikov commented on cypress/e2e/searchBoxAutoFill.cy.js
> +})
We already possess the specification file for this US - headerSearchBox.cy.js. Please compose your test within that file. Additionally, ensure that your test is properly aligned.

2024-11-23 06:08 UTC, LanaUno commented on cypress/e2e/searchBoxAutoFill.cy.js
> +})
> We already possess the specification file for this US - headerSearchBox.cy.js. Please compose your test within that file. Additionally, ensure that your test is properly aligned

Ok, but how I can do this?

2024-11-23 18:51 UTC, LanaUno commented on cypress/e2e/searchBoxAutoFill.cy.js
> +})
I deleted previous file [searchBoxAutoFill.cy.js], added my test to  headerSearchBox.cy.js. Tests passed locally.

2024-11-23 22:16 UTC, Olena-Novikova reviewed
Super!

2024-11-24 18:01 UTC, LanaUno commented on cypress/e2e/searchBoxAutoFill.cy.js
> +})
After such a long time waiting for review this branch has conflicts which I can't resolve by myself, I heed help

2024-11-24 20:29 UTC, LanaUno commented on cypress/e2e/searchBoxAutoFill.cy.js
> +})
> > After such a long time waiting for review this branch has conflicts which I can't resolve by myself, I heed help
> 
> Consider utilizing Nalya’s review, which demonstrates a step-by-step resolution of conflicts. Additionally, I noticed that you have not deleted the newly created file. Kindly delete the file and align your test accordingly.

Conflict is resolved, could you please approve PR?

2024-11-24 20:40 UTC, adiuzhikov commented on cypress/e2e/searchBoxAutoFill.cy.js
> +})
Once more, you are editing the incorrect file (a newly created one). Please delete that file and make all changes with your test in the existing one. Kindly adhere to the instructions provided.

2024-11-25 12:59 UTC, adiuzhikov approved these changes

2024-11-25 13:49 UTC, Olena-Novikova reviewed
Good job.

2024-11-25 13:54 UTC, Olena-Novikova approved these changes

2024-11-25 13:54 UTC, merged