TC_01.002.03 | FreestyleProject > Rename Project | Rename a project from the Dashboard page using Cyrillic
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #328
Opened 2024-11-23 16:45 UTC by yanaoreshkevich

![yi0sjVL7A5](https://github.com/user-attachments/assets/674eca8e-8107-41d3-b4d5-3bd48a192fe7)

US: https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/21
TC: https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/223

2024-11-23 17:24 UTC, ivanlashkevich approved these changes
The test passed successfully. Approved.

2024-11-24 00:42 UTC, adiuzhikov requested changes

2024-11-24 00:42 UTC, adiuzhikov commented on cypress/e2e/freestyleProjectRenameProject.cy.js
> +  it.only('TC_01.002.03 | Rename a project from the Dashboard page using Cyrillic', () => {
Please, remove .only()

2024-11-24 08:31 UTC, yanaoreshkevich commented on cypress/e2e/freestyleProjectRenameProject.cy.js
> +  it.only('TC_01.002.03 | Rename a project from the Dashboard page using Cyrillic', () => {
Yes, thanks for noticing this)

2024-11-24 18:46 UTC, merged