Add RF_14.002.15
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #404
Opened 2024-11-26 18:59 UTC by LanaUno

![image](https://github.com/user-attachments/assets/8d380798-8d1b-424d-b762-cc690cb68ae8)

2024-11-26 21:47 UTC, QA-LilyArslanova commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +    newJobPage.addNewProjectName("New Folder TC_14.002.15_A")
Just a heads-up: if 'pro' is added to the folder name, it will cause the test to fail

2024-11-27 05:10 UTC, LanaUno commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +    newJobPage.addNewProjectName("New Folder TC_14.002.15_A")
> Just a heads-up: if 'pro' is added to the folder name, it will cause the test to fail

This test passes just fine, the reason of the fail is that some variables were changed and other test still contain old names.

2024-11-27 06:38 UTC, LanaUno commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +    newJobPage.addNewProjectName("New Folder TC_14.002.15_A")
This test fails 
![image](https://github.com/user-attachments/assets/6f2d0a4b-0a0c-45cc-889e-2cff58c165ec)

2024-11-27 20:01 UTC, adiuzhikov requested changes

2024-11-27 20:01 UTC, adiuzhikov commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +  it("TC_14.002.06 | Multiple matches are displayed on the result page", () => {
I noticed you made some changes to someone else’s tests. Could you please revert those changes and leave the original version as it is? Make changes to your own tests only. Don't use Format Document feature, but you definitely can utilize Format Selection!

2024-11-27 20:23 UTC, LanaUno commented on cypress/e2e/headerSearchBoxPOM.cy.js
> -
> Could you please return the empty line to its original position? I intentionally left it blank to make it easier to navigate before importing the Page Objects and fixture files. Thanks a bunch!

I deleted it upon Nalya request

2024-11-27 20:25 UTC, LanaUno commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +  it("TC_14.002.06 | Multiple matches are displayed on the result page", () => {
I didn't changed anybody's tests. Maybe it was prettier?

2024-11-27 20:39 UTC, adiuzhikov commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +  it("TC_14.002.06 | Multiple matches are displayed on the result page", () => {
Maybe it was, but you cannot push such test

2024-11-27 20:54 UTC, LanaUno commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +  it("TC_14.002.06 | Multiple matches are displayed on the result page", () => {
It's already done. I can't discard those changes even I want to. All test pass. For future I will know, thank you for saying this.

2024-11-27 20:57 UTC, adiuzhikov commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +  it("TC_14.002.06 | Multiple matches are displayed on the result page", () => {
Certainly, you can revert the changes to all the tests in the file. However, we had discussed this multiple times that we should not modify someone else’s code. Therefore, please revert the code back to its original state and create a new commit.

2024-11-27 21:01 UTC, adiuzhikov commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +  it("TC_14.002.06 | Multiple matches are displayed on the result page", () => {
Additionally, you are welcome to apply other project rules, such as the creation of a pull request (PR).
* PR title should be identical to your RF card title.
* PR description should include a link to your RF card.

2024-11-28 05:25 UTC, LanaUno commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +  it("TC_14.002.06 | Multiple matches are displayed on the result page", () => {
> Additionally, you are welcome to apply other project rules, such as the creation of a pull request (PR).
> 
> * PR title should be identical to your RF card title.
> * PR description should include a link to your RF card.

sure)

2024-11-28 05:27 UTC, LanaUno commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +  it("TC_14.002.06 | Multiple matches are displayed on the result page", () => {
> Certainly, you can revert the changes to all the tests in the file. However, we had discussed this multiple times that we should not modify someone else’s code. Therefore, please revert the code back to its original state and create a new commit.

Again, It was done upon Nalya request.

2024-11-28 13:39 UTC, adiuzhikov commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +  it("TC_14.002.06 | Multiple matches are displayed on the result page", () => {
> Again, It was done upon Nalya request.

Again, if you are unwilling to edit your test in accordance with the project’s guidelines, I will not approve it.

2024-11-28 17:10 UTC, NShakiro commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +import PipelinePage from "../pageObjects/PipelinePage";
Although it's a good idea to reparate pages and fixtures inports, if want to follow some design patterns we need to say it to all collaborators after discussing it with project leads, thanks.

2024-11-28 17:12 UTC, NShakiro commented on cypress/e2e/headerSearchBoxPOM.cy.js
> +    newJobPage.addNewProjectName("New Folder TC_14.002.15_A")
issue was resolved

2024-11-28 17:26 UTC, NShakiro approved these changes

2024-11-28 17:27 UTC, merged