RF_06.005.03 | Delete Organization Folder from project status table o…
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #474
Opened 2024-11-29 07:02 UTC by Alzhan-B

Converting TC_06.005.03 to POM

2024-11-29 07:11 UTC, AnDerova approved these changes

2024-11-29 08:50 UTC, ivanlashkevich requested changes
And could you please:
- fill in the description field in your github board card;
- write down your 'RF' to your US card.

2024-11-29 08:50 UTC, ivanlashkevich commented on cypress/pageObjects/DashboardPage.js
> +  getJenkinsHomeLink = () => cy.get('[id="jenkins-home-link"]')
We already have this locator named 'getJenkinsLogo'. As the logo relates to the header it is located in the Header.js file. So, delete the new added locator 'getJenkinsHomeLink' and replace in your test with the existing one.

2024-11-29 08:50 UTC, ivanlashkevich commented on cypress/pageObjects/DashboardPage.js
> +  clickJenkinsHomeLinkImage() {
We also have such method 'clickJenkinsLogo ()' that redirects the user to the Dashboard page. The same as the locator, it is located in the 'Header.js' file. So, replace it in your test.

2024-11-29 14:21 UTC, Alzhan-B commented on cypress/pageObjects/DashboardPage.js
> +  getJenkinsHomeLink = () => cy.get('[id="jenkins-home-link"]')
Thanks, Ivan, for pointing this out. Good catch! I deleted my selector from DashboardPage.js and used the one from the Header.js.

2024-11-29 14:24 UTC, Alzhan-B commented on cypress/pageObjects/DashboardPage.js
> +  clickJenkinsHomeLinkImage() {
Thanks! I also deleted my "clickJenkinsHomeLinkImage()" method from Dashboard.js and used the one you recommended from the Header.js -  'clickJenkinsLogo ()'.

2024-11-29 14:46 UTC, Alzhan-B commented
> And could you please:
> 
> * fill in the description field in your github board card;
> * write down your 'RF' to your US card.

Could you elaborate please? My RF card has links to 1) PR, 2) US and 3) TC that is being refactored. I am not sure I am following you. Thanks!

2024-11-29 14:47 UTC, ivanlashkevich commented on cypress/pageObjects/DashboardPage.js
> +  getJenkinsHomeLink = () => cy.get('[id="jenkins-home-link"]')
Alzhan, good job! Thank you! Approved.

2024-11-29 14:48 UTC, ivanlashkevich approved these changes

2024-11-29 14:52 UTC, ivanlashkevich commented
> > And could you please:
> > 
> > * fill in the description field in your github board card;
> > * write down your 'RF' to your US card.
> 
> Could you elaborate please? My current RF_06.005.03 card has links to 1) PR, 2) US, and 3) TC that is being refactored. I am not sure I am following you. What needs to be corrected? Thanks!

After the 'RF' github board card has been created, you shoul go to the US card, scroll down to 'Add a comment' section and write down your 'RF number and test case name' (e.g. RF_06.005.03 Delete Organization Folder from project status table on Dashboard page)

2024-11-29 15:13 UTC, merged

2024-11-29 15:15 UTC, Alzhan-B commented
> > > And could you please:
> > > 
> > > * fill in the description field in your github board card;
> > > * write down your 'RF' to your US card.
> > 
> > 
> > Could you elaborate please? My current RF_06.005.03 card has links to 1) PR, 2) US, and 3) TC that is being refactored. I am not sure I am following you. What needs to be corrected? Thanks!
> 
> After the 'RF' github board card has been created, you should go to the US card, scroll down to 'Add a comment' section and write down your 'RF number and test case name' (e.g. RF_06.005.03 Delete Organization Folder from project status table on Dashboard page). [Follow the link.](https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/34)

Thank you, Ivan! Done.

2024-11-30 23:05 UTC, Negrescu29 commented on cypress/pageObjects/DashboardPage.js
> +  getWelcomeToJenkins = () => cy.get('.empty-state-block h1');
@Alzhan-B 

you introduced a duplicate locator `getWelcomeToJenkins` an identical locator is just one line above `getWelcomeToJenkinsHeadline` when you a chance would you please remove the duplicated locator? thanks