Ss/04.001 10 a
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #613
Opened 2024-12-04 03:44 UTC by GhSeredenko

New TC_04.001.10_A | Rename folder from drop-down menu

2024-12-04 03:51 UTC, Sandarella requested changes
Залила вместе с .only для свое теста. 
Нужно скорректировать - убрать метод, и добавить это новым коммитом в этот же пулл. Коммит назови полностью как называется it. После аппрувов нажмешь сквош

2024-12-04 04:39 UTC, Sandarella approved these changes

2024-12-04 14:47 UTC, adiuzhikov commented
Kindly ensure that you adhere to the principles of PR creation:

* **PR Title:** The PR title should be identical to the title of your TC card on the board.
* **PR Description:** The PR description should include a link to your TC card.

2024-12-05 12:59 UTC, GhSeredenko commented on package.json
Hi, @Negrescu29 I only add the test without changing the structure of package-lock.json

2024-12-05 13:39 UTC, Negrescu29 commented on package.json
I'm going from what I see in your commit. maybe these weren't intentional changes 

<img width="969" alt="Screenshot 2024-12-05 at 14 37 45" src="https://github.com/user-attachments/assets/8d42076d-1927-400f-ad4c-0deb9ef2f8ff">

2024-12-05 17:55 UTC, GhSeredenko commented on package.json
@Negrescu29 Can you please give an idea how to fix it?

2024-12-05 19:08 UTC, Negrescu29 commented on package.json
you need to revert your commit and stage/ commit only the changes related to the spec files.

2024-12-06 19:46 UTC, NShakiro reviewed
You probably need to pull new POM

2024-12-07 19:55 UTC, Rom-T commented on cypress/e2e/oldTests/folderRenameFolder.cy.js
> +    it.only('TC_04.001.10|Rename folder from drop-down menu', () => {
Please remove only

2024-12-07 20:31 UTC, GhSeredenko commented
> Залила вместе с .only для свое теста. Нужно скорректировать - убрать метод, и добавить это новым коммитом в этот же пулл. Коммит назови полностью как называется it. После аппрувов нажмешь сквош

Спасибо за рекомендацию. Убрала only. Название коммита обновила

2024-12-07 20:32 UTC, GhSeredenko commented on package.json
@Negrescu29 Thank you, fixed all additional changes

2024-12-07 20:32 UTC, GhSeredenko commented on cypress/e2e/oldTests/createFolder.cy.js
> +
Ok, fixed

2024-12-07 20:36 UTC, Sandarella approved these changes

2024-12-07 21:03 UTC, Negrescu29 approved these changes

2024-12-08 03:52 UTC, merged

2024-12-08 12:27 UTC, Sandarella commented
@GhSeredenko Света, удали пожалуйста ветку здесь и у себя локально.

2024-12-08 18:33 UTC, GhSeredenko commented
@Sandarella Thank you, deleted the brunch.