TC_01.004.02-OD | FreestyleProject > Delete Project on Project Page
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #629
Opened 2024-12-05 21:26 UTC by Olga-QA-USA

https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/62

2024-12-06 14:36 UTC, razman0v approved these changes

2024-12-06 14:55 UTC, Sandarella approved these changes

2024-12-06 15:43 UTC, adiuzhikov requested changes

2024-12-06 15:43 UTC, adiuzhikov commented on cypress/e2e/oldTests/freestyleDeleteProjectFromProjectPage.cy.js
> +describe("US_01.004 | FreestyleProject > Delete Project", () => {
Could you please explain the rationale behind removing `.skip` from the old test?

2024-12-06 15:43 UTC, adiuzhikov commented on cypress/e2e/dashboardCreateViewPOM.cy.js
> +describe.skip("US_16.002 | Dashboard > Create View", () => {
Why would you .skip the whole describe here?

2024-12-06 15:43 UTC, adiuzhikov commented on cypress/e2e/oldTests/freestyleDeleteProjectFromProjectPage.cy.js
> +});
As we discussed during the last review, we won’t be formatting the entire document. You can go ahead and edit your block of code as needed.

2024-12-06 18:40 UTC, Olga-QA-USA commented on cypress/e2e/oldTests/freestyleDeleteProjectFromProjectPage.cy.js
> +describe("US_01.004 | FreestyleProject > Delete Project", () => {
My team mates said me that.

2024-12-06 18:49 UTC, Olga-QA-USA commented on cypress/e2e/oldTests/freestyleDeleteProjectFromProjectPage.cy.js
> +describe("US_01.004 | FreestyleProject > Delete Project", () => {
And I double check with Nalya

2024-12-06 18:50 UTC, Olga-QA-USA commented on cypress/e2e/oldTests/freestyleDeleteProjectFromProjectPage.cy.js
> +});
I see, I just do Auo formatting for whole document

2024-12-06 19:00 UTC, NShakiro commented on cypress/e2e/oldTests/freestyleDeleteProjectFromProjectPage.cy.js
> +describe("US_01.004 | FreestyleProject > Delete Project", () => {
since she want to add a new old test, she may reopen describe to add her test and make sure it's passing and later she will need to skip it

2024-12-06 19:34 UTC, adiuzhikov commented on cypress/e2e/oldTests/freestyleDeleteProjectFromProjectPage.cy.js
> +});
We do not do that on the project, but you can always format your block of code -> select your test and click Format Selection

2024-12-06 19:37 UTC, adiuzhikov commented on cypress/e2e/oldTests/freestyleDeleteProjectFromProjectPage.cy.js
> +describe("US_01.004 | FreestyleProject > Delete Project", () => {
That makes sense! No need to run the whole describe. 

@Olga-QA-USA, could you please make the changes we discussed in this thread?

2024-12-10 03:55 UTC, Olga-QA-USA commented on cypress/e2e/oldTests/freestyleDeleteProjectFromProjectPage.cy.js
> +describe("US_01.004 | FreestyleProject > Delete Project", () => {
I add it.only for my test

2024-12-10 04:40 UTC, merged