Od/tc 00.002.16
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #632
Opened 2024-12-05 23:01 UTC by Olga-QA-USA

TC_00.002.16 | New Item > Create Pipeline Project #631

2024-12-06 03:45 UTC, Olga-QA-USA commented
создала ERR_004 |TC_16.002.02 | Dashboard > Create View | Sort items in the view для этой ошибки
<img width="1440" alt="Screenshot 2024-12-05 at 22 41 01" src="https://github.com/user-attachments/assets/4583e046-27eb-4096-84be-9f35c4609393">

2024-12-06 04:35 UTC, antonbloha reviewed
test should be written using POM approach.

2024-12-06 14:55 UTC, Sandarella approved these changes

2024-12-06 15:49 UTC, adiuzhikov requested changes
Please review the two previous reviews and adhere to the following guidelines:
1. We do not remove `.skip` from old tests. If you wish to write tests in the old format, you are welcome to do so, but you are not required to remove `.skip`.
2. We do not format code written by others.
3. The PR title should be the same as the TC card name.

2024-12-07 01:47 UTC, NShakiro approved these changes

2024-12-10 03:52 UTC, Olga-QA-USA commented on cypress/e2e/dashboardCreateViewPOM.cy.js
> +describe.skip("US_16.002 | Dashboard > Create View", () => {
It works locally in my computer also, I delete skip already.

2024-12-10 04:38 UTC, adiuzhikov approved these changes

2024-12-10 04:40 UTC, merged