nm/TC #67
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #68
Opened 2024-11-18 00:10 UTC by Ridgewood2016

2024-11-18 20:26 UTC, Ridgewood2016 commented
https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/25

2024-11-19 02:03 UTC, Negrescu29 requested changes

2024-11-19 02:03 UTC, Negrescu29 commented on cypress/e2e/folderRenameFolder.cy.js
> +const PASSWORD = Cypress.env('local.admin.password');
These 2 variables (USERNAME, PASSWORD) are not used in this test, better to remove.

2024-11-19 02:14 UTC, Ridgewood2016 commented on cypress/e2e/folderRenameFolder.cy.js
> +const PASSWORD = Cypress.env('local.admin.password');
@Negrescu29  Fixed, please approve

2024-11-19 02:14 UTC, Negrescu29 approved these changes
👍🏼

2024-11-19 03:10 UTC, adiuzhikov commented on cypress/e2e/folderRenameFolder.cy.js
> +            cy.wait(1000)
Is it necessary to use .wait() here?

2024-11-19 03:10 UTC, adiuzhikov commented on cypress/e2e/folderRenameFolder.cy.js
> +            cy.get('input[name="name"]').clear()
Why do you need to .clear() the input?

2024-11-19 03:10 UTC, adiuzhikov commented on cypress/e2e/folderRenameFolder.cy.js
> +            cy.get('div[id="main-panel"]').contains('Error')
Looks like your test doesn't have an assertion - so what do you check here?

2024-11-19 03:55 UTC, Ridgewood2016 commented
@adiuzhikov Fixed. Please approve

2024-11-19 04:01 UTC, adiuzhikov commented
You still don't have an assertion in the test. Please, use .should() or .expect() instead of .contains()

2024-11-19 04:13 UTC, Ridgewood2016 commented
@adiuzhikov . fixed. Please check.

2024-11-19 13:29 UTC, closed without merging

2024-11-19 13:30 UTC, Ridgewood2016 commented
Need to rework