Log out from Jenkins
RedRoverSchool/JenkinsQA_JS_2024_fall pull request #76
Opened 2024-11-18 12:38 UTC by KateVernikovskaya

https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/28

2024-11-18 16:06 UTC, Negrescu29 requested changes
Please see comment

2024-11-18 16:06 UTC, Negrescu29 commented on cypress/e2e/headerClickLogOut.cy.js
> +        cy.get('[href="/logout"] > .hidden-xs').contains('выход').click()
@KateVernikovskaya in the latest lesson 14.(11_16) Alina mentioned that Jenkins should be in English otherwise the test will fail for other people.

line 5: contains('выход')

2024-11-19 05:58 UTC, KateVernikovskaya commented on cypress/e2e/headerClickLogOut.cy.js
> +        cy.get('[href="/logout"] > .hidden-xs').contains('выход').click()
Thank you!

2024-11-19 06:27 UTC, KateVernikovskaya commented on cypress/e2e/headerClickLogOut.cy.js
> +        cy.get('[href="/logout"] > .hidden-xs').contains('выход').click()
I added corrections

2024-11-19 08:31 UTC, KateVernikovskaya commented
> Kate! Good job! The provided code works correctly. Approved.

Thank you!-)

2024-11-19 14:31 UTC, Negrescu29 approved these changes

2024-11-19 14:35 UTC, Negrescu29 reviewed
@KateVernikovskaya for the future a note regarding the name of your branch, please follow the guidelines.

your TC:  TC_14.003.01
-https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/71 

so the branch name should be: kv/TC_14.003-01


<img width="927" alt="Screenshot 2024-11-19 at 15 32 23" src="https://github.com/user-attachments/assets/9e9cb0b5-64a9-4183-b9ff-e2fdf2c76b2f">

2024-11-19 15:18 UTC, KateVernikovskaya commented
Thank you!

2024-11-20 03:53 UTC, NShakiro approved these changes

2024-11-20 05:48 UTC, merged